export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const LIBRARY_ROUTE = '/'
export const USER_LIBRARY_ROUTE = '/userLibrary'
export const BOOK_ROUTE = '/book'